version: '3'
services:
  todo-api-server:
    image: todo-api-server
    build: ./backend/
    ports:
      - "4000:4000"
    networks:
      - todo-app  
    depends_on:
      - mongo
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules

  todo-client:
    image: todo-client
    build: ./client/
    ports:
      - "3000:3000"
    stdin_open: true
    networks:
      - todo-app
    volumes:
      - ./client/:/usr/src/app
      - /usr/src/app/node_modules

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - todo-app
    volumes:
      - todo-data:/data/db

networks:
  todo-app:
    driver: bridge

volumes:
  todo-data:
    driver: local


